server:
  port: 8203

eureka:
  instance:
    hostname: eureka8203                          # eureka 服务端的实例名称
  client:
    register-with-eureka: false                   # false 代表 eureka 不注册自己
    fetch-registry: false                         # false 表示自己就是注册中心，不需要去检索服务
    service-url:
      # 设置 eureka 的地址
      defaultZone: http://eureka8201.com:8201/eureka/,http://eureka8202.com:8202/eureka/