server:
  port: 8202

eureka:
  instance:
    hostname: eureka8202.com                      # eureka 服务端的实例名称
  client:
    register-with-eureka: false                   # false 代表 eureka 不注册自己
    fetch-registry: false                         # false 表示自己就是注册中心，不需要去检索服务
    service-url:
      # 设置 eureka 的地址
      defaultZone: http://eureka8201.com:8201/eureka/,http://eureka8203.com:8203/eureka/