server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka8201.com:8201/eureka/,http://eureka8202.com:8202/eureka/,http://eureka8203.com:8203/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /cnmd                                 # 设置统一前缀
  routes:
    deptproxy.serviceId: microservice-dept
    deptproxy.path: /deptproxy/**
  ignored-services: "*"                         # 禁止真实服务名访问，如果要禁止所有的使用过 <"*">

info:
  app.name: microservice
  company.name: www.404NotFound.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}